In [4]:
import numpy

In [6]:
a=[[1,2],[3,4]]
na=numpy.asarray(a)
print(na)

[[1 2]
 [3 4]]


In [8]:
na

array([[1, 2],
       [3, 4]])

In [10]:
na[0:1,:1]

array([[1]])

In [11]:
a = numpy.array([[1],[2],[3]])
b = numpy.array([[2],[3],[4]])
c = numpy.hstack((a,b))
print(c)

[[1 2]
 [2 3]
 [3 4]]


In [12]:
a = numpy.array([[1],[2],[3]])
b = numpy.array([[2],[3],[4]])
c = numpy.vstack((a,b))
print(c)

[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [14]:
a = numpy.array([[1,11],[2,22],[3,77]])
b = numpy.array([[2,55],[3,45],[4,32]])
c = numpy.vstack((a,b))
print(c)

[[ 1 11]
 [ 2 22]
 [ 3 77]
 [ 2 55]
 [ 3 45]
 [ 4 32]]


In [18]:
 x = numpy.arange(16).reshape(4, 4)

In [19]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
y=numpy.hsplit(x,4)

In [21]:
print(y)

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
